name: profit-pipeline   

on:
  push:
    branches:
      - main

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        id: setup-pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Configure AWS credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        id: install-dependencies
        run: pnpm install

      - name: Build workspace
        id: build
        run: pnpm run build

      - name: Build and push backend
        id: build-and-push-backend
        run: |
          IMAGE=public.ecr.aws/g2p9a1c6/rocketseat/profit-backend
          TAG=${{ github.sha }}

          docker build -f apps/backend/Dockerfile -t $IMAGE:$TAG .
          docker tag $IMAGE:$TAG $IMAGE:latest

          docker push $IMAGE:$TAG
          docker push $IMAGE:latest

      - name: Build and push frontend
        run: |
          IMAGE=public.ecr.aws/g2p9a1c6/rocketseat/profit-frontend
          TAG=${{ github.sha }}

          docker build -f apps/frontend/Dockerfile -t $IMAGE:$TAG .
          docker tag $IMAGE:$TAG $IMAGE:latest

          docker push $IMAGE:$TAG
          docker push $IMAGE:latest