name: profit-pipeline   

on:
  push:
    branches:
      - main

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        id: setup-pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Configure AWS credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        id: install-dependencies
        run: pnpm install

      - name: Build workspace
        id: build
        run: pnpm run build

      - name: Run tests
        id: tests
        run: pnpm run test

      - name: Generate tag
        id: generate-tag
        run: echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push backend
        id: build-and-push-backend
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_BACKEND_REPOSITORY: ${{ vars.ECR_BACKEND_REPOSITORY }}
          IMAGE_TAG: ${{ steps.generate-tag.outputs.TAG }}
        run: |
          IMAGE=${{ env.ECR_REGISTRY }}/${{vars.DEFAULT_ALIAS}}/${{ env.ECR_BACKEND_REPOSITORY }}

          docker build -f apps/backend/Dockerfile -t $IMAGE:$IMAGE_TAG .

          docker push $IMAGE:$IMAGE_TAG

      - name: Build and push frontend
        id: build-and-push-frontend
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_FRONTEND_REPOSITORY: ${{ vars.ECR_FRONTEND_REPOSITORY }}
          IMAGE_TAG: ${{ steps.generate-tag.outputs.TAG }}
        run: |
          IMAGE=${{ env.ECR_REGISTRY }}/${{vars.DEFAULT_ALIAS}}/${{ env.ECR_FRONTEND_REPOSITORY }}

          docker build -f apps/frontend/Dockerfile -t $IMAGE:$IMAGE_TAG .

          docker push $IMAGE:$IMAGE_TAG