name: profit-pipeline   

on:
  push:
    branches:
      - main

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        id: setup-pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Configure AWS credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        id: install-dependencies
        run: pnpm install

      - name: Build workspace
        id: build
        run: pnpm run build

      - name: Run tests
        id: tests
        run: pnpm run test

      - name: Generate tag
        id: generate-tag
        run: echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      
      - name: Build backend
        id: build-backend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: apps/backend/Dockerfile
          load: true
          push: false
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ vars.DEFAULT_ALIAS }}/${{ vars.ECR_BACKEND_REPOSITORY }}:${{ steps.generate-tag.outputs.TAG }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      
      - name: Build frontend
        id: build-frontend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: apps/frontend/Dockerfile
          load: true
          push: false
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ vars.DEFAULT_ALIAS }}/${{ vars.ECR_FRONTEND_REPOSITORY }}:${{ steps.generate-tag.outputs.TAG }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Run Trivy vulnerability scanner backend
        id: trivy-backend
        uses: aquasecurity/trivy-action@0.33.1
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_BACKEND_REPOSITORY: ${{ vars.ECR_BACKEND_REPOSITORY }}
        with:
          image-ref: ${{ env.ECR_REGISTRY }}/${{vars.DEFAULT_ALIAS}}/${{ env.ECR_BACKEND_REPOSITORY }}:${{ steps.generate-tag.outputs.TAG }}
          format: 'table'
          ignore-unfixed: true
          scanners: vuln
          skip-dirs: /usr/local/lib/node_modules
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

        
      - name: Run Trivy vulnerability scanner frontend
        id: trivy-frontend
        uses: aquasecurity/trivy-action@0.33.1
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_FRONTEND_REPOSITORY: ${{ vars.ECR_FRONTEND_REPOSITORY }}
        with:
          image-ref: ${{ env.ECR_REGISTRY }}/${{vars.DEFAULT_ALIAS}}/${{ env.ECR_FRONTEND_REPOSITORY }}:${{ steps.generate-tag.outputs.TAG }}
          format: 'table'
          ignore-unfixed: true
          scanners: vuln
          skip-dirs: /usr/local/lib/node_modules
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Push Docker Image backend
        run: docker push ${{ steps.login-ecr.outputs.registry }}/${{ vars.DEFAULT_ALIAS }}/${{ vars.ECR_BACKEND_REPOSITORY }}:${{ steps.generate-tag.outputs.TAG }}

      - name: Push Docker Image frontend
        run: docker push ${{ steps.login-ecr.outputs.registry }}/${{ vars.DEFAULT_ALIAS }}/${{ vars.ECR_FRONTEND_REPOSITORY }}:${{ steps.generate-tag.outputs.TAG }}